
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  application:
    name: schools
  datasource:
    url: jdbc:mariadb://localhost:3306/springboot_mariadb
    username: root
    password: 1007
  jpa:
    hibernate:
      ddl-auto: create
application:
  config:
    student-url: http://localhost:8222/api/v1/students
